package com.example.createnote.model;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SampleData {

    public static List<Note> data;

    public static List<Note> getData(){
        data = new ArrayList<>();

        SimpleDateFormat fmt = new SimpleDateFormat("yyyyMMdd hh:mm:ss");
        try {
            data.add(new Note(1, "Lorem ipsum dolor", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pretium aenean pharetra magna ac. Amet risus nullam eget felis eget nunc lobortis. Congue quisque egestas diam in. Praesent semper feugiat nibh sed. Sem nulla pharetra diam sit amet nisl. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. Platea dictumst quisque sagittis purus sit amet. Lectus quam id leo in vitae turpis massa sed elementum. Amet massa vitae tortor condimentum lacinia quis. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Id semper risus in hendrerit gravida rutrum. Curabitur gravida arcu ac tortor. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Turpis egestas integer eget aliquet nibh praesent. Nulla at volutpat diam ut venenatis. Ultrices tincidunt arcu non sodales neque sodales ut. Ultrices tincidunt arcu non sodales neque sodales ut.", Category.INDIGO, false, null, (Date)fmt.parse("20190823 06:30:56"), fmt.parse("20190823 07:28:45")));
            data.add(new Note(2, "Dolor sit amet", "Eget aliquet nibh praesent tristique magna sit. Dui ut ornare lectus sit. Augue ut lectus arcu bibendum. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida cum. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Leo urna molestie at elementum eu facilisis. Consequat id porta nibh venenatis cras sed felis eget. In tellus integer feugiat scelerisque. In dictum non consectetur a erat. Nulla facilisi etiam dignissim diam quis enim. Mi in nulla posuere sollicitudin aliquam ultrices sagittis.", Category.PURPLE, false, null, fmt.parse("20190920 07:42:41"), fmt.parse("20190920 08:11:55")));
            data.add(new Note(3, "Dolor sit amet", "Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Sem nulla pharetra diam sit amet nisl. Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Orci dapibus ultrices in iaculis nunc sed augue lacus. Mi proin sed libero enim sed faucibus turpis in. Ut porttitor leo a diam sollicitudin tempor id. Adipiscing bibendum est ultricies integer quis auctor elit sed. Purus in massa tempor nec feugiat nisl. Tempus imperdiet nulla malesuada pellentesque elit eget. Nibh nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Massa massa ultricies mi quis hendrerit dolor magna eget. Magna fringilla urna porttitor rhoncus dolor. Elit eget gravida cum sociis natoque penatibus et. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Tempor commodo ullamcorper a lacus vestibulum sed. Cras adipiscing enim eu turpis egestas pretium. Quis varius quam quisque id diam vel quam elementum pulvinar. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus.", Category.ORANGE, false, null, fmt.parse("20190901 04:44:34"), fmt.parse("20190901 05:14:57")));
            data.add(new Note(4, "Ultrices mi tempus", "Ultrices mi tempus imperdiet nulla malesuada. Nibh ipsum consequat nisl vel pretium lectus quam. Vitae semper quis lectus nulla. Neque convallis a cras semper auctor neque vitae. Sit amet nisl suscipit adipiscing bibendum est ultricies. Condimentum lacinia quis vel eros donec ac odio tempor orci. Eros in cursus turpis massa tincidunt dui ut ornare lectus. Sit amet cursus sit amet dictum. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Maecenas pharetra convallis posuere morbi leo urna molestie at elementum. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Velit sed ullamcorper morbi tincidunt. Vivamus at augue eget arcu dictum varius duis at consectetur. Proin sed libero enim sed faucibus turpis in. Quis risus sed vulputate odio ut. Mi sit amet mauris commodo. Id neque aliquam vestibulum morbi blandit. Metus dictum at tempor commodo ullamcorper.", Category.INDIGO, true, fmt.parse("20191017 11:14:35"), fmt.parse("20190824 09:26:03"), fmt.parse("20190824 10:11:45")));
            data.add(new Note(5, "Amet consectetur adipiscing", "Amet consectetur adipiscing elit pellentesque. Sit amet risus nullam eget felis eget. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Mauris vitae ultricies leo integer malesuada nunc vel risus. Scelerisque purus semper eget duis. Vitae purus faucibus ornare suspendisse. Purus viverra accumsan in nisl nisi scelerisque eu ultrices. Ut aliquam purus sit amet luctus. Lobortis mattis aliquam faucibus purus in massa tempor. Eu augue ut lectus arcu bibendum at varius. Consectetur adipiscing elit pellentesque habitant morbi tristique senectus et netus. Praesent elementum facilisis leo vel fringilla. Bibendum ut tristique et egestas quis. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat.", Category.INDIGO, true, fmt.parse("20191017 11:14:35"), fmt.parse("20190824 09:26:03"), fmt.parse("20190824 10:11:45")));
            data.add(new Note(6, "Amet consectetur adipiscing", "Amet consectetur adipiscing elit duis tristique sollicitudin. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Aliquam sem et tortor consequat id. Justo eget magna fermentum iaculis. Posuere ac ut consequat semper viverra nam libero. Netus et malesuada fames ac turpis egestas sed tempus. Maecenas pharetra convallis posuere morbi leo urna molestie. Mi ipsum faucibus vitae aliquet nec ullamcorper. Nibh sit amet commodo nulla facilisi nullam vehicula ipsum a. Fermentum et sollicitudin ac orci phasellus egestas. Augue mauris augue neque gravida in fermentum et. Nisl vel pretium lectus quam id. Accumsan in nisl nisi scelerisque. Eu augue ut lectus arcu bibendum at varius.", Category.PURPLE, false, null, fmt.parse("20190914 03:00:20"), fmt.parse("20190914 03:48:39")));
            data.add(new Note(7, "Sed velit dignissim", "Sed velit dignissim sodales ut eu. Vulputate sapien nec sagittis aliquam malesuada bibendum. Nisi porta lorem mollis aliquam ut porttitor leo. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius sit. Nisi porta lorem mollis aliquam. Molestie nunc non blandit massa enim nec dui nunc. Iaculis at erat pellentesque adipiscing commodo elit at. Vestibulum mattis ullamcorper velit sed ullamcorper. Magna etiam tempor orci eu lobortis elementum nibh tellus. Quis imperdiet massa tincidunt nunc pulvinar. Porttitor eget dolor morbi non arcu risus quis varius quam. Lectus urna duis convallis convallis tellus id. At auctor urna nunc id. Elit pellentesque habitant morbi tristique senectus et netus et malesuada.", Category.INDIGO, true, fmt.parse("20191009 07:10:37"), fmt.parse("20190914 10:29:30"), fmt.parse("20190914 10:46:00")));
            data.add(new Note(8, "Feugiat in ante", "Feugiat in ante metus dictum at tempor commodo ullamcorper a. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Lorem ipsum dolor sit amet consectetur adipiscing elit ut aliquam. Nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Tellus id interdum velit laoreet id donec. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Ultrices mi tempus imperdiet nulla malesuada pellentesque. In ante metus dictum at tempor commodo.", Category.PURPLE, true, fmt.parse("20191012 12:14:40"), fmt.parse("20190829 10:25:12"), fmt.parse("20190829 11:02:36")));
            data.add(new Note(9, "Augue lacus viverra", "Augue lacus viverra vitae congue eu consequat ac felis. Integer malesuada nunc vel risus commodo viverra maecenas accumsan. Ac feugiat sed lectus vestibulum mattis ullamcorper. Neque convallis a cras semper auctor neque vitae tempus. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. In eu mi bibendum neque egestas congue quisque egestas. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Eu consequat ac felis donec. Quam id leo in vitae turpis. Maecenas accumsan lacus vel facilisis volutpat est velit egestas. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Viverra vitae congue eu consequat. Risus nullam eget felis eget. Odio euismod lacinia at quis risus sed vulputate odio ut.", Category.ORANGE, true, fmt.parse("20190923 09:54:49"), fmt.parse("20190907 03:44:29"), fmt.parse("20190907 04:13:44")));
            data.add(new Note(10, "Leo duis ut", "Leo duis ut diam quam nulla porttitor. Pellentesque dignissim enim sit amet. In hac habitasse platea dictumst quisque sagittis purus sit amet. Nibh mauris cursus mattis molestie a iaculis at. Quam lacus suspendisse faucibus interdum posuere. Quisque egestas diam in arcu cursus euismod quis. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Facilisis magna etiam tempor orci eu. Lectus mauris ultrices eros in cursus turpis massa. Tellus cras adipiscing enim eu turpis egestas.", Category.ORANGE, true, fmt.parse("20190927 02:50:22"), fmt.parse("20190904 07:29:16"), fmt.parse("20190904 07:42:20")));
            data.add(new Note(10, "Dictumst vestibulum rhoncus", "", Category.PURPLE, true, fmt.parse("20190930 07:25:56"), fmt.parse("20190904 02:04:43"), fmt.parse("220190904 02:21:00")));
            data.add(new Note(11, "Eu lobortis elementum", "", Category.PURPLE, true, fmt.parse("20190930 04:11:35"), fmt.parse("20190912 07:24:25"), fmt.parse("20190912 08:23:29")));
            data.add(new Note(12, "Libero volutpat sed", "", Category.GREEN, true, fmt.parse("20191005 04:42:13"), fmt.parse("20190919 07:30:55"), fmt.parse("20190919 07:48:22")));
            data.add(new Note(13, "Ac placerat vestibulum", "", Category.INDIGO, true, fmt.parse("20190929 06:31:06"), fmt.parse("20190912 02:59:08"), fmt.parse("20190912 03:53:42")));
            data.add(new Note(14, "Est ullamcorper eget", "", Category.GREEN, false, null, fmt.parse("20190827 04:46:01"), fmt.parse("20190827 04:54:14")));
            data.add(new Note(15, "Mi proin sed", "", Category.GREEN, false, null, fmt.parse("20190922 10:00:03"), fmt.parse("20190922 10:12:37")));
            data.add(new Note(16, "Ac auctor augue", "", Category.BLUE, true, fmt.parse("20191010 02:23:06"), fmt.parse("20190826 11:41:10"), fmt.parse("20190827 12:12:17")));
            data.add(new Note(17, "Arcu risus quis", "", Category.YELLOW, false, null, fmt.parse("20190829 10:12:47"), fmt.parse("20190829 10:28:05")));
            data.add(new Note(18, "Sit amet cursus", "", Category.ORANGE, false, null, fmt.parse("20190914 06:27:38"), fmt.parse("20190914 07:23:22")));
            data.add(new Note(19, "Mauris nunc congue", "", Category.RED, false, null, fmt.parse("20190828 03:18:48"), fmt.parse("20190828 03:57:03")));



        }
        catch (ParseException e)
        {
            //should not happen
        }
                return data;
    }

}
